name: github_tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  # job to run unit tests
  unit_tests:
    # configure the operating system "environment"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      # get to branch
      - uses: actions/checkout@v2
      # get the proper environment
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: S4S
          environment-file: environment.yml
      - run: cd tests/unit |
        python test_data_processor.py |
        python test_plotter.py
  # job to run functional tests
  func_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: S4S
          environment-file: environment.yml
      - run: cd tests/func |
        bash testdata_processor.sh |
        bash testplotter.sh
  # job to run pycodestyle
  code_style:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: S4S
          environment-file: environment.yml
      - run: pycodestyle $(git ls-files "*.py")

